--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8
-- Dumped by pg_dump version 16.8

-- Started on 2025-06-28 22:48:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16700)
-- Name: arabalar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.arabalar (
    gunluk_fiyat double precision NOT NULL,
    musait boolean NOT NULL,
    yil integer NOT NULL,
    id bigint NOT NULL,
    marka character varying(255),
    model character varying(255)
);


ALTER TABLE public.arabalar OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16699)
-- Name: arabalar_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.arabalar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arabalar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16708)
-- Name: kiralamalar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kiralamalar (
    baslangic_tarihi date,
    bitis_tarihi date,
    toplam_fiyat double precision NOT NULL,
    araba_id bigint NOT NULL,
    id bigint NOT NULL,
    kullanici_id bigint NOT NULL,
    adres character varying(500),
    tc_no character varying(255),
    telefon character varying(255)
);


ALTER TABLE public.kiralamalar OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16707)
-- Name: kiralamalar_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kiralamalar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kiralamalar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16715)
-- Name: kullanici_rolleri; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kullanici_rolleri (
    rol_id integer NOT NULL,
    kullanici_id bigint NOT NULL
);


ALTER TABLE public.kullanici_rolleri OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16721)
-- Name: kullanicilar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kullanicilar (
    enabled boolean NOT NULL,
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    password character varying(64) NOT NULL
);


ALTER TABLE public.kullanicilar OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16720)
-- Name: kullanicilar_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kullanicilar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kullanicilar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16729)
-- Name: roller; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roller (
    id integer NOT NULL,
    name character varying(45) NOT NULL
);


ALTER TABLE public.roller OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16728)
-- Name: roller_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roller ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roller_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4918 (class 0 OID 16700)
-- Dependencies: 216
-- Data for Name: arabalar; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.arabalar (gunluk_fiyat, musait, yil, id, marka, model) FROM stdin;
1700	t	2024	3	Ford	Focus
3500	t	2023	4	BMW	320i
1500	f	2023	1	Toyota	Corolla
2500	t	2015	5	Mercedes-Benz	A180d
2750	t	2023	6	Mercedes-Benz	E250
\.


--
-- TOC entry 4920 (class 0 OID 16708)
-- Dependencies: 218
-- Data for Name: kiralamalar; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kiralamalar (baslangic_tarihi, bitis_tarihi, toplam_fiyat, araba_id, id, kullanici_id, adres, tc_no, telefon) FROM stdin;
2025-06-29	2025-07-02	4500	1	1	2	100.Yıl Karabük Merkez	26989146690	05317887577
\.


--
-- TOC entry 4921 (class 0 OID 16715)
-- Dependencies: 219
-- Data for Name: kullanici_rolleri; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kullanici_rolleri (rol_id, kullanici_id) FROM stdin;
1	1
2	2
2	3
1	4
\.


--
-- TOC entry 4923 (class 0 OID 16721)
-- Dependencies: 221
-- Data for Name: kullanicilar; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kullanicilar (enabled, id, username, password) FROM stdin;
t	1	admin	12345
t	2	user	123
t	3	eneseminucar	0707
t	4	ucaradmin	0606
\.


--
-- TOC entry 4925 (class 0 OID 16729)
-- Dependencies: 223
-- Data for Name: roller; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roller (id, name) FROM stdin;
1	ADMIN
2	USER
\.


--
-- TOC entry 4931 (class 0 OID 0)
-- Dependencies: 215
-- Name: arabalar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.arabalar_id_seq', 6, true);


--
-- TOC entry 4932 (class 0 OID 0)
-- Dependencies: 217
-- Name: kiralamalar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kiralamalar_id_seq', 1, true);


--
-- TOC entry 4933 (class 0 OID 0)
-- Dependencies: 220
-- Name: kullanicilar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kullanicilar_id_seq', 4, true);


--
-- TOC entry 4934 (class 0 OID 0)
-- Dependencies: 222
-- Name: roller_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roller_id_seq', 2, true);


--
-- TOC entry 4755 (class 2606 OID 16706)
-- Name: arabalar arabalar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arabalar
    ADD CONSTRAINT arabalar_pkey PRIMARY KEY (id);


--
-- TOC entry 4757 (class 2606 OID 16714)
-- Name: kiralamalar kiralamalar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kiralamalar
    ADD CONSTRAINT kiralamalar_pkey PRIMARY KEY (id);


--
-- TOC entry 4759 (class 2606 OID 16719)
-- Name: kullanici_rolleri kullanici_rolleri_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kullanici_rolleri
    ADD CONSTRAINT kullanici_rolleri_pkey PRIMARY KEY (rol_id, kullanici_id);


--
-- TOC entry 4761 (class 2606 OID 16725)
-- Name: kullanicilar kullanicilar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kullanicilar
    ADD CONSTRAINT kullanicilar_pkey PRIMARY KEY (id);


--
-- TOC entry 4763 (class 2606 OID 16727)
-- Name: kullanicilar kullanicilar_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kullanicilar
    ADD CONSTRAINT kullanicilar_username_key UNIQUE (username);


--
-- TOC entry 4767 (class 2606 OID 16735)
-- Name: roller roller_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roller
    ADD CONSTRAINT roller_name_key UNIQUE (name);


--
-- TOC entry 4769 (class 2606 OID 16733)
-- Name: roller roller_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roller
    ADD CONSTRAINT roller_pkey PRIMARY KEY (id);


--
-- TOC entry 4765 (class 2606 OID 16757)
-- Name: kullanicilar uketonw5u9o9d703su7k8jxljdr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kullanicilar
    ADD CONSTRAINT uketonw5u9o9d703su7k8jxljdr UNIQUE (username);


--
-- TOC entry 4772 (class 2606 OID 16746)
-- Name: kullanici_rolleri fk4ahaxfs92eps1wa9tfoyjwmjj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kullanici_rolleri
    ADD CONSTRAINT fk4ahaxfs92eps1wa9tfoyjwmjj FOREIGN KEY (rol_id) REFERENCES public.roller(id);


--
-- TOC entry 4773 (class 2606 OID 16751)
-- Name: kullanici_rolleri fkaalorljfbqji146yqgn99er1c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kullanici_rolleri
    ADD CONSTRAINT fkaalorljfbqji146yqgn99er1c FOREIGN KEY (kullanici_id) REFERENCES public.kullanicilar(id);


--
-- TOC entry 4770 (class 2606 OID 16736)
-- Name: kiralamalar fkgay9pacw1k32yme1bh4fvtase; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kiralamalar
    ADD CONSTRAINT fkgay9pacw1k32yme1bh4fvtase FOREIGN KEY (araba_id) REFERENCES public.arabalar(id);


--
-- TOC entry 4771 (class 2606 OID 16741)
-- Name: kiralamalar fkq7xkeotbabiog78axiskj4wwa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kiralamalar
    ADD CONSTRAINT fkq7xkeotbabiog78axiskj4wwa FOREIGN KEY (kullanici_id) REFERENCES public.kullanicilar(id);


-- Completed on 2025-06-28 22:48:54

--
-- PostgreSQL database dump complete
--

